import { onCall, HttpsError } from "firebase-functions/v2/https";
import { db } from "../lib/admin.js";
import { requireAuth, requireString } from "../lib/guards.js";
import { GEMINI_API_KEY } from "../lib/secrets.js";
import { getGateway } from "../ai/index.js";
import type { Lang, Match } from "../domain.js";

/**
 * Returns per-language match preview + facts. Generated by Gemini ONCE per
 * (match, language) and cached in Firestore, so thousands of fans share one
 * generation rather than triggering one call each (see ADR-4, efficiency).
 */
export const getMatchContent = onCall(
  { enforceAppCheck: true, secrets: [GEMINI_API_KEY] },
  async (req) => {
    requireAuth(req);
    const matchId = requireString(req.data?.matchId, "matchId", 100);
    const lang = normaliseLang(req.data?.lang);

    const contentRef = db.doc(`matches/${matchId}/content/${lang}`);
    const cached = await contentRef.get();
    if (cached.exists) {
      return cached.data();
    }

    const matchSnap = await db.doc(`matches/${matchId}`).get();
    if (!matchSnap.exists) {
      throw new HttpsError("not-found", "Match not found.");
    }

    const match = matchSnap.data() as Match;
    const { preview, facts } = await getGateway().matchContent(match, lang);
    const payload = { lang, preview, facts, generatedAt: Date.now() };
    await contentRef.set(payload);
    return payload;
  }
);

function normaliseLang(value: unknown): Lang {
  return value === "es" || value === "fr" ? value : "en";
}
